"""ClientV1

Revision ID: d151823b1a21
Revises: 
Create Date: 2024-10-30 20:46:03.701787

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d151823b1a21"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("avatar", sa.LargeBinary(), nullable=True),
        sa.Column(
            "gender",
            sa.Enum("male", "female", "other", name="genderenum"),
            nullable=True,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("surname", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clients_id"), "clients", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_clients_id"), table_name="clients")
    op.drop_table("clients")
    # ### end Alembic commands ###
