"""ClientV5

Revision ID: 606d7703135f
Revises: 3e7fc93b8062
Create Date: 2024-10-31 03:33:27.721247

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "606d7703135f"
down_revision: Union[str, None] = "3e7fc93b8062"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
