"""Client V4

Revision ID: 3e7fc93b8062
Revises: d74aba0d1c51
Create Date: 2024-10-31 03:17:03.795681

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e7fc93b8062"
down_revision: Union[str, None] = "d74aba0d1c51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clients", sa.Column("latitude", sa.Float(), nullable=True))
    op.add_column("clients", sa.Column("longitude", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "longitude")
    op.drop_column("clients", "latitude")
    # ### end Alembic commands ###
